name: CI and Deploy to Fly.io

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Go dependencies
      run: make deps

    - name: Run tests
      run: make test

    - name: Install Fly CLI
      run: curl -sSL https://fly.io/install.sh | sh

    - name: Fly.io login
      run: fly auth login --access-token ${{ secrets.FLY_API_TOKEN }}

    - name: Deploy to Fly.io
      if: success()
      run: |
        flyctl launch --remote-only --app ${{ secrets.FLY_APP_NAME }}
        flyctl deploy --app ${{ secrets.FLY_APP_NAME }} --dockerfile Dockerfile
