name: CI and Deploy to Fly.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Go dependencies
      run: make deps

    - name: Run tests
      run: make test

    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only --app ${{ secrets.FLY_APP_NAME }}
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - run: cd frontend && npm run build
      env:
        VITE_API_URL: https://${{ secrets.FLY_APP_NAME }}.fly.dev/api/v1

    - name: Set Git identity
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public